spring: 
   datasource:
    #数据源配置 
    url:  jdbc:mysql://localhost:3306/material?useUnicode=true&characterEncoding=utf-8   
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #连接池配置
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query:  SELECT *
      connection-properties: characterEncoding=utf8
   
   #配置文件上传
   http: 
    multipart:
      max-file-size: 2000Mb  #max file size 默认 1M 
      max-request-size: 2500Mb  #max request size 默认10m

encrypt:
   failOnError: true   #遇到错误继续
    
logging:               #配置日志
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUGGER

    